### ISSUE TITLE
Unable to navigate to PlayingView after some songs were removed

### ISSUE THREAD

**Issue by Spring3** [ashinzekene/react-music-player#11]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS and Version?
> MacOS High Sierra 10.13.6

### Versions
  > Node 8.11.3
  > React 15.6.1

### Repro steps
  > Add a decent amount of songs (let's say 6)
  > Play the last song
  > Click on the white area below the progress bar at the bottom to navigate to PlayingView
  > Use the hamburger menu to return back to the home page
  > Remove 3  songs before the currently playing one (before the last one)
  > Try to navigate back to PlayingView
  > You can't 😱 

### The log given by the failure.
> No errors printed

### Mention any other details that might be useful.
Check the gif for better understanding. My guess would be that the problem here is because the song can not be found anymore by the component (probably the index update issue), because on gif you can clearly see that after some songs are removed, the name of the current song, that is displayed below the progress bar resets to `[No song]`

![oct-04-2018 04-51-43](https://user-images.githubusercontent.com/4171202/46448790-5086d880-c791-11e8-868b-3b3f55d61772.gif)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ashinzekene** [comment]
Would look into this

**Comment by ashinzekene** [comment]
I think this has been fixed
